### ISSUE TITLE
this is annoying me

### ISSUE THREAD

**Issue by ghost** [DoctorMcKay/node-stats-reporter#1]
TypeError: Cannot read property 'length' of undefined
    at Timeout.reportStats [as _onTimeout] (/home/card/node_modules/@doctormckay/stats-reporter/index.js:86:22)
    at ontimeout (timers.js:475:11)
    at Timer.unrefdHandle (timers.js:588:5)

**Comment by ghost** [comment]
happens atleat once a day

**Comment by DoctorMcKay** [comment]
Does your machine somehow not have a CPU?

**Comment by DoctorMcKay** [comment]
This should be fixed in 1.0.4, so just run npm update.
